---
title: "Bird Study"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(readr)
library(dplyr)
library(janitor)
```

```{r}
webpage <- read_html("https://www.pwrc.usgs.gov/bbl/manual/speclist.cfm")

tbls <- html_nodes(webpage, "table") %>% 
    html_table(fill = TRUE)

species <- tbls[[1]] %>% 
    clean_names() %>% 
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))
```
## Read in Utqiagvik_predator_surveys.csv from web URL
```{r}
predSurveys_original <- read.csv(url("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A9ffec04c-7e2d-41dd-9e88-b6c2e8c4375e"))
head(predSurveys_original)
```
## Read in Utqiagvik_nest_data.csv from web URL
```{r}
nestDataoriginal <- read.csv(url("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A982bd2fc-4edf-4da7-96ef-0d11b853102d"))
head(nestDataoriginal)
```
## Join tables.
```{r}
predSurveys_joined <- left_join(predSurveys_original, species, by = c("species" = "alpha_code"))
```

## Create a function
```{r}
species_func <- function(L.table, R.table){
  joined <- left_join(L.table, R.table, by = c("species" = "alpha_code"))
  return(joined)
}

```
## Use function on Pred data
```{r}
predSurveys_joined2 <- species_func(predSurveys_original, species)


```
## Use function on Nest data
```{r}
nestData_join <- species_func(nestDataoriginal, species)
```
## Summarize
```{r}
pred_count <- predSurveys_joined2 %>% 
  group_by(year, common_name) %>% 
  summarise("predator_count" = sum(count, na.rm = T), .groups = "drop") %>% 
  filter(!is.na(common_name))

head(pred_count)
```
## Plot
```{r}
library(ggplot2)

ggplot(pred_count, mapping = aes(x = year, y = predator_count, color = common_name)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Num Predators") +
  theme_bw()
  
```

